/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CurrencyConverter;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author 20231230
 */
public class CurrencyConverter extends javax.swing.JFrame {

    /**
     * Creates new form CurrencyConverter
     */
    public CurrencyConverter() {
        initComponents();
        setSize(724, 580);
        setResizable(false);  
        setLocationRelativeTo(null);
    }
    
private static final String API_KEY = "8359b2d8255244df9912618038c4c460"; // Replace with your API key
private static final String API_URL = "https://openexchangerates.org/api/latest.json?app_id=" + API_KEY;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtAmountConverted = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtAmount = new javax.swing.JTextField();
        jToCurrency = new javax.swing.JComboBox<>();
        jFromCurrency = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jbtnReset = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnConverter2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 10));
        jPanel2.setForeground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel1.setText("Amount Converted");

        jtxtAmountConverted.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jtxtAmountConverted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAmountConvertedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jtxtAmountConverted, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtAmountConverted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 690, 90));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 10));
        jPanel3.setForeground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 56)); // NOI18N
        jLabel2.setText("Currency Converter");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 690, 100));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 10));
        jPanel4.setForeground(new java.awt.Color(0, 102, 102));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel3.setText("From");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel5.setText("To");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel6.setText("Amount");

        jtxtAmount.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jtxtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAmountActionPerformed(evt);
            }
        });

        jToCurrency.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jToCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EUR - Euro", "USD - US Dollar", "AUD - Australian Dollar ", "BRL - Brazilian Real ", "RUB - Russian Ruble", "CAD - Canadian Dollar", "CHF - Swiss Franc ", "CNY - Chinese Yuan", "GBP - Britain", "INR - Indian Rupee", "JPY - Japanese Yen", "KRW - South Korean Won", "MXN - Mexican Peso", "NZD - New Zealand Dollar", "SGD - Singapore Dollar", "ZAR - South African Rand" }));
        jToCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToCurrencyActionPerformed(evt);
            }
        });

        jFromCurrency.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jFromCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EUR - Euro", "USD - US Dollar", "AUD - Australian Dollar ", "BRL - Brazilian Real ", "RUB - Russian Ruble", "CAD - Canadian Dollar", "CHF - Swiss Franc ", "CNY - Chinese Yuan", "GBP - Britain", "INR - Indian Rupee", "JPY - Japanese Yen", "KRW - South Korean Won", "MXN - Mexican Peso", "NZD - New Zealand Dollar", "SGD - Singapore Dollar", "ZAR - South African Rand" }));
        jFromCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFromCurrencyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToCurrency, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtAmount, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFromCurrency, 0, 493, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jFromCurrency))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jToCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 690, 170));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 10));
        jPanel5.setForeground(new java.awt.Color(0, 102, 102));

        jbtnReset.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jbtnConverter2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jbtnConverter2.setText("Convert");
        jbtnConverter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConverter2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jbtnConverter2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnReset)
                    .addComponent(jbtnExit)
                    .addComponent(jbtnConverter2))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 690, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtAmountConvertedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAmountConvertedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAmountConvertedActionPerformed

    private void jtxtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAmountActionPerformed

    private void jToCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToCurrencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToCurrencyActionPerformed

    private void jFromCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFromCurrencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFromCurrencyActionPerformed
private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
         frame = new JFrame ("Exit");
         if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Currency Converter", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)  {
             System.exit(0);
         }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
         jtxtAmount.setText("");
         jtxtAmountConverted.setText("");
         jFromCurrency.setSelectedIndex(-1); 
         jToCurrency.setSelectedIndex(-1); 
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnConverter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConverter2ActionPerformed
         double amount; 
         String fromCurrency;
         String toCurrency; 
         double convertAmount;
         
         try {
                amount = Double.parseDouble(jtxtAmount.getText());
         } catch (NumberFormatException e) {
             JOptionPane.showMessageDialog(this, "Please enter a valid number", "Exclamation", JOptionPane.ERROR_MESSAGE);
             jtxtAmount.setText("");
             jtxtAmount.requestFocus();
             return;
         }
         fromCurrency = jFromCurrency.getSelectedItem().toString().substring(0, 3);
         toCurrency = jToCurrency.getSelectedItem().toString().substring(0, 3);
                 
         convertAmount = convertCurrency(amount,  fromCurrency, toCurrency);
         String formattedAmount = String.format("%.2f", convertAmount);

        jtxtAmountConverted.setText(amount + " " + fromCurrency + " = " + formattedAmount + " " + toCurrency);
    }//GEN-LAST:event_jbtnConverter2ActionPerformed

    
    //=======================================================================================
 //   public  double convertCurrency(double amount, String fromCurrency, String toCurrency) {
     //   Map<String, Double> conversionRate = new HashMap<>();
        //conversionRate.put("GBP", 1.0);
 //       conversionRate.put("EUR", 1.35);
 //       
  //      if (! conversionRate.containsKey(fromCurrency) || !conversionRate.containsKey(toCurrency)) {
    //        throw new IllegalArgumentException("Invalid currency code.");
     //   }
        
     //   return amount * conversionRate.get(toCurrency) / conversionRate.get(fromCurrency);
  //  }
    

    

    public double convertCurrency(double amount, String fromCurrency, String toCurrency) {
        try {
            // Fetch exchange rates from the API
            String apiUrl = API_URL;
            String response = sendHttpRequest(apiUrl);
            
            // Parse the JSON response
            JsonObject jsonObject = JsonParser.parseString(response).getAsJsonObject();
            JsonObject rates = jsonObject.getAsJsonObject("rates");

            double fromRate = rates.get(fromCurrency).getAsDouble();
            double toRate = rates.get(toCurrency).getAsDouble();
            
            // Convert the amount
            return amount * (toRate / fromRate);
        } catch (Exception e) {
            e.printStackTrace();
            return 0;
        }
    }

    private String sendHttpRequest(String apiUrl) throws Exception {
        URL url = new URL(apiUrl);
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        connection.setRequestMethod("GET");
        
        BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()));
        String inputLine;
        StringBuilder content = new StringBuilder();
        
        while ((inputLine = in.readLine()) != null) {
            content.append(inputLine);
        }
        
        // Close the connections
        in.close();
        connection.disconnect();
        
        return content.toString();
    }
    //=======================================================================================
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrencyConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jFromCurrency;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox<String> jToCurrency;
    private javax.swing.JButton jbtnConverter2;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JTextField jtxtAmount;
    private javax.swing.JTextField jtxtAmountConverted;
    // End of variables declaration//GEN-END:variables
}

